In [1]:
# Import relevant libraries
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib as mat
import matplotlib.pyplot as plt
import plotly.express as px
# exclude warnings - ingore warnings generated by libraries
import warnings
warnings.filterwarnings("ignore")


- import dataset
- dataset "Social_Media_Usage" classifies the social media platforms used by males and females of different ages 
- Generates a model to predict platforms used by a 21yr old female and a 32 yr old male

In [2]:
# create dataframework for the dataset
Social = pd.read_csv("Social_Media_Usage.csv")
Social

    age   gender   platform
0    20   female     tiktok
1    23   female     tiktok
2    25   female     tiktok
3    26   female   snapchat
4    29   female   snapchat
5    29   female   snapchat
6    30   female    twitter
7    31   female    twitter
8    33   female    twitter
9    37   female    twitter
10   20     male     tiktok
11   21     male     tiktok

Split dataset - to enable answering of questions

prior to that

Exploratory Data Analysis
- looking at dataset
- understanding it
- understanding data types of variables
- looking at distribution of each of the variables
- removing null values or missing data
- dealing with different redundancies in dataset

For this data set
gender - categorical data
platform - categorical data
age - continuous data

In [6]:
# Change gender variable into a numeric data using pandas - to easily analyse
t = pd
Social["gender"].replace(['female', 'male'], [0, 1], inplace=True)
Social

    age   gender   platform
0    20   female     tiktok
1    23   female     tiktok
2    25   female     tiktok
3    26   female   snapchat
4    29   female   snapchat
5    29   female   snapchat
6    30   female    twitter
7    31   female    twitter
8    33   female    twitter
9    37   female    twitter
10   20     male     tiktok
11   21     male     tiktok

In [55]:
Social["gender"] = Social["gender"].astype(str)    # needed
Social["gender"] = Social["gender"].replace(["female", "male", np.nan], [0, 1, -1])   # worked
Social

    age   gender   platform
0    20   female     tiktok
1    23   female     tiktok
2    25   female     tiktok
3    26   female   snapchat
4    29   female   snapchat
5    29   female   snapchat
6    30   female    twitter
7    31   female    twitter
8    33   female    twitter
9    37   female    twitter
10   20     male     tiktok
11   21     male     tiktok

When splitting - need to know what is already known
what is the input?

for this dataset we need to undestand what is already known?
- ages for 20-27, what platforms they would use and what genders they fall in

In [39]:
# The data needs to be split so as to predict the output 

# In this case we first drop the column 'platform' which is what we are trying to predict 

X = Social.drop(columns=['platform'])
X

    age   gender
0    20   female
1    23   female
2    25   female
3    26   female
4    29   female
5    29   female
6    30   female
7    31   female
8    33   female
9    37   female
10   20     male
11   21     male

In [40]:
# Generate the predictor output set of dataset - gives what platforms will be used by the individuals

Y = Social['platform']
Y

0        tiktok
1        tiktok
2        tiktok
3      snapchat
4      snapchat
5      snapchat
6       twitter
7       twitter
8       twitter
9       twitter
10       tiktok
11       tiktok
Name: platform, dtype: object

datatype of Y is object; object refers to categorical datatype

In [41]:
# Building the model (using the Decision Tree classification method)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [57]:
# train the model using the X(input set) and Y(output set)
model.fit(X, Y)

ValueError: could not convert string to float: ' female'

In [56]:
# make predictions using the desifned model to determine platforms used by a 21yr female and 32 yr male
prediction = model.predict([[21, 0], [32, 1]])
prediction

AttributeError: 'DecisionTreeClassifier' object has no attribute 'tree_'

Rule of Thumb for Allocation of data sets for training and testing
Default 
- 70-80% for training model
- 20-30% for test for testing the model

Accuracy scores range from 0 - 1

- The accuracy score ranges from 0-1. The returned value shows the model is 100% accurately makes the prediction 
- However, accuracies are also affected by the test size used

In [ ]:
# train_test_split - for testing accuracy of models
from sklearn.model_selection import train_test_split
# then we generate the accuracy scores that result from prediction
from sklearn.metrics import accuracy_score

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

prediction = model.predict(X_test)
 
score = accuracy_score(Y_test, prediction)
score

In [ ]:
# if the test size is 30% of the data 

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

prediction = model.predict(X_test)

score2 = accuracy_score(Y_test, prediction)
score2

with 30%, the accuracy level reduces to 50% - not a good score therefore something has to be twicked

In [ ]:
# Save model the trained model as a joblib file 

from sklearn.externals import joblib
joblib.dumb(model, 'Social Media Predictor.joblib')

# prediction model is saved as 'Social Media Predictor.joblib'

Trees - how the model learned to predict that if you give me this age group i should pin point that social medial platform

In [ ]:
# Generate the decision tree output 

tree.export_graphviz(model, out_file = 'Social Media Predictor.dot', feature_names = ['age', 'gender'], class_names = sorted(Y.unique()), label= 'all', rounded = True, filled= True)